version: "3.9"
services:
  folderlog:
    image: ghcr.io/diegocjorge/folderlog:latest
    container_name: folderlog
    volumes:
      - ./folder1:/watched/folder1:ro
      - ./folder2:/watched/folder2:ro
      - ./logs:/logs
    environment:
      - LOG_EXT=.txt
    # - EXCLUDE_REGEX=.*\.tmp   #optional
    restart: unless-stopped