version: "3.9"
services:
  folderlog:
    image: ghcr.io/diegocjorge/folderlog:latest
    container_name: folderlog
    volumes:
      - ./folder1:/watched/folder1:ro
      - ./folder2:/watched/folder2:ro
      - ./logs:/logs
    environment:
      - TZ=America/Sao_Paulo
      - LOG_EXT=.txt
    # - EXCLUDE_REGEX=.*(\.partial|\.tmp|\.swp|~)$   #OPTIONAL, in this exemple it excludes files ending with .partial, .tmp, .swp, or ~ (most common temporary files)
    restart: unless-stopped