version: "3.9"
services:
  folderlog:
    image: ghcr.io/diegocjorge/folderlog:latest
    container_name: folderlog
    volumes:
      # You can place one or multiple directories inside ./watched,
      # or map specific folders directly as shown below:
      - ./folder1:/watched/folder1:ro
      - ./folder2:/watched/folder2:ro
      - ./logs:/logs
    environment:
      - LOG_EXT=.txt  # Change to desired log file extension, e.g. .txt (.log is default)

      # Example 1: ignore temporary files ending with ".tmp"
      - EXCLUDE_REGEX=.*\.tmp  

      # Example 2: ignore everything inside "node_modules" directories
      # (useful when monitoring project folders to avoid noise)
      # - EXCLUDE_REGEX=.*/node_modules/.*  

    restart: unless-stopped